version = 1

# Simple data files containing metadata, settings, etc.
[[annotations]]
path = [
    "VERSION",
    "continuous_integration/requirements-build.txt",
    "scripts/pre-commit/shellcheckrc",
    "docs/legate/switcher.json",
    "share/legate/sanitizers/lsan_suppressions.txt",
    "share/legate/sanitizers/ubsan_suppressions.txt",
    "share/legate/sanitizers/tsan_default_options.txt",
    "share/legate/sanitizers/ubsan_default_options.txt",
    "share/legate/sanitizers/asan_default_options.txt",
    "share/legate/sanitizers/asan_default_options_gpu.txt",
    "share/legate/sanitizers/tsan_suppressions.txt",
    "src/cmake/versions/*.json",
    "src/cmake/versions/legion_version.json",
    "src/python/legate/legate_jupyter.json",
    "src/cmake/presets/*.json",
    "src/CMakePresets.json"
]
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved."
SPDX-License-Identifier = "Apache-2.0"

# Patches for other projects we build.
[[annotations]]
path = [
    "src/cmake/patches/**"
]
SPDX-FileCopyrightText = "Copyright (c) 2022-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved."
SPDX-License-Identifier = "Apache-2.0"

# Image files.
[[annotations]]
path = [
    "docs/figures/developer_build.png",
    "docs/figures/streaming_example_1.png",
    "docs/legate/source/manual/usage/images/stream_activity.png",
    "docs/legate/source/manual/usage/images/cg_matmul.png",
    "docs/legate/source/manual/usage/images/profile.png",
    "docs/legate/source/manual/usage/images/nsys_ui.png",
    "docs/legate/source/manual/usage/images/cg_zoomed.png",
    "docs/legate/source/manual/usage/images/cg_gpudev.png",
    "docs/legate/source/manual/usage/images/cg_channel.png",
    "docs/legate/source/manual/usage/images/cg_profile.png",
    "docs/legate/source/manual/usage/images/prof_box.png",
    "docs/legate/source/manual/usage/images/cg_dottask.png",
    "docs/legate/source/manual/usage/images/cg_boxes.png",
    "docs/legate/source/manual/usage/images/cg_gaps.png"
]
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved."
SPDX-License-Identifier = "Apache-2.0"
