# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
LEGION_GIT_URL:
  - https://gitlab.com/StanfordLegion/legion.git
LEGION_GIT_SHALLOW:
  - false
rust_min_version:
  - "1.84"
c_stdlib:
  - sysroot
c_stdlib_version:
  - "2.28"
