name: Mac build and test

concurrency:
  group: mac-ci-build-and-test-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  schedule:
    # Runs at 08:00 UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test (mac, cpu, release-gcc, no_ucx)
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      platform: mac
      target-device: cpu
      cmake-preset: release-gcc
      ucx-enabled: false
    secrets: inherit
