# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES.
#                         All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
name: Mac build and test

concurrency:
  group: >-
    ${{
      (github.ref == 'refs/heads/main' || startsWith(github.ref_name, 'branch-')) &&
      format('{0}-{1}', github.workflow, github.run_id) ||
      format('{0}-{1}', github.workflow, github.ref_name)
    }}
  cancel-in-progress: true

on:
  # Disabled until the CI scripts are in working order again.
  # schedule:
  #   # Runs at 08:00 UTC every day
  #   - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test (mac, cpu, release, ucx)
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      platform: mac
      target-device: cpu
      build-type: ci
      build-mode: release
      build-has-tests: true
      network: ucx
      refname: ${{ github.ref_name }}
      default-branch: ${{ github.event.repository.default_branch }}
    secrets: inherit
